import React, { Component } from "react";
import Image from "react-bootstrap/Image";

import shakespeareImage from "../../assets/shakespeare.jpg";

import "./about.scss";

export default class About extends Component {
  render() {
    return (
      <div className="about">
        <p className="aboutText">
          Can a machine learning model learn to write like Shakespeare? A
          Recurrent Neural Network (RNN) trained on lines from 715 characters
          from Shakespeare's plays aims to do just that. With inspiration from
          Branav Kumar Gnanamoorthy's{" "}
          <a href="https://medium.com/@gnabr/rnns-to-write-like-shakespeare-226609863cd1">
            implementation
          </a>{" "}
          of such an RNN, this site demonstrates the results of 500 plays
          generated by my attempt at creating a Shakespeare writing RNN.
        </p>
        <div className="imageContainer">
          <Image src={shakespeareImage} roundedCircle fluid />
        </div>
        <p className="aboutTextTwo"></p>
      </div>
    );
  }
}
